### ISSUE TITLE
minimumの最後に

### ISSUE THREAD

**Issue by tarosay** [kamataryo/crosskeys-console-mobile#1]
`</body></html>`が抜けているのではないでしょうか？

**Comment by kamataryo** [comment]
あ、消えちゃってました。半手動でやったせいです。

**Comment by tarosay** [comment]
了解です。
Closeしますね。

**Comment by kamataryo** [comment]
これ、最小化のためには書かない方が正しいかったです。
htmlでは一部のタグが省略できます。
https://www.w3.org/TR/html5/syntax.html#optional-tags
